---
title: "Simuations for rankLasso"
output: html_notebook
---

## Data Generation

```{r}

n<-c(100,200,300,400) #number of samples
p<-c(100,400,900,1600) #number of variables
p_0<-c(3,10,20) #number of true variables

```


```{r}
rmvn <- function(n, mu=0, V = matrix(1)){
  p <- length(mu)
  if(any(is.na(match(dim(V),p))))
    stop("Dimension problem!")
  D <- chol(V)
  (matrix(rnorm(n*p), ncol=p)%*%D + rep(mu,rep(n,p)))
}

':=' <- function(lhs, rhs) {
  frame <- parent.frame()
  lhs <- as.list(substitute(lhs))
  if (length(lhs) > 1)
    lhs <- lhs[-1]
  if (length(lhs) == 1) {
    do.call(`=`, list(lhs[[1]], rhs), envir=frame)
    return(invisible(NULL)) 
  }
  if (is.function(rhs) || is(rhs, 'formula'))
    rhs <- list(rhs)
  if (length(lhs) > length(rhs))
    rhs <- c(rhs, rep(list(NULL), length(lhs) - length(rhs)))
  for (i in 1:length(lhs))
    do.call(`=`, list(lhs[[i]], rhs[[i]]), envir=frame)
  return(invisible(NULL)) 
}


data_gen_1<-function(n,p,p_0)
{
  X<-rmvn(n,rep(0,p),diag(p))
  beta<-c(rep(3,p_0),rep(0,p-p_0))
  ep<-rcauchy(n,0,1)
  Y=X%*%beta + ep
  return(list(X,beta,Y))
}

data_gen_2<-function(n,p,p_0)
{
  p1 <- runif(p,0.1,0.5)
  X <- lapply(1:p,function(x) sample(0:2, size = n, replace = TRUE, prob = c(p1[x]*p1[x], 2*p1[x]*(1-p1[x]), (1-p1[x])^2))
)
  X<-data.frame(X)
  colnames(X)<-NULL
  X<-as.matrix(X)
  X<-as.matrix(scale(X))
  beta<-c(rep(3,p_0),rep(0,p-p_0))
  ep<-rcauchy(n,0,1)
  Y=X%*%beta + ep
  return(list(X,beta,Y))
}

data_gen_3<-function(n,p,p_0)
{
  ma<-matrix(data=0.3,nrow=p,ncol = p)
  diag(ma)<-rep(1,p)
  X<-rmvn(n,rep(0,p),ma)
  beta<-c(rep(3,p_0),rep(0,p-p_0))
  ep<-rcauchy(n,0,1)
  Y=X%*%beta + ep
  return(list(X,beta,Y))
}

data_gen_4<-function(n,p,p_0)
{
  ma<-matrix(data=0.3,nrow=p,ncol = p)
  diag(ma)<-rep(1,p)
  X<-rmvn(n,rep(0,p),ma)
  beta<-c(rep(3,p_0),rep(0,p-p_0))
  ep<-rcauchy(n,0,1)
  Y= exp(4+ 0.5*(X%*%beta))  + ep
  return(list(X,beta,Y))
}

```




## Implimentation

### RankLasso-1

```{r}
library(glmnet)

lambda_rl<-function(p,n){
  return(0.3*sqrt(log(p)/n))
}

weights_arl<-function(lambda,beta)
{
w<- sapply(1:length(beta), function(x) ifelse(abs(beta[x]) > 0.1*lambda,0.1*lambda/abs(beta[x]),1/abs(beta[x])))
return(w)
}

lambda_lad<-function(p,n){
  return(1.5*sqrt(log(p)/n))
}

fp_rl_1<-rep(0,200)
fn_rl_1<-rep(0,200)
tp_rl_1<-rep(0,200)
nmp_1<-matrix(0,nrow = 3,ncol = 4)
fdr_1<-matrix(0,nrow = 3,ncol = 4)
power_1<-matrix(0,nrow = 3,ncol = 4)

fp_arl_1<-rep(0,200)
fn_arl_1<-rep(0,200)
tp_arl_1<-rep(0,200)
nmp_arl_1<-matrix(0,nrow = 3,ncol = 4)
fdr_arl_1<-matrix(0,nrow = 3,ncol = 4)
power_arl_1<-matrix(0,nrow = 3,ncol = 4)


fp_thrl_1<-rep(0,200)
fn_thrl_1<-rep(0,200)
tp_thrl_1<-rep(0,200)
nmp_thrl_1<-matrix(0,nrow = 3,ncol = 4)
fdr_thrl_1<-matrix(0,nrow = 3,ncol = 4)
power_thrl_1<-matrix(0,nrow = 3,ncol = 4)

fp_lad_1<-rep(0,200)
fn_lad_1<-rep(0,200)
tp_lad_1<-rep(0,200)
nmp_lad_1<-matrix(0,nrow = 3,ncol = 4)
fdr_lad_1<-matrix(0,nrow = 3,ncol = 4)
power_lad_1<-matrix(0,nrow = 3,ncol = 4)

fp_lasso_1<-rep(0,200)
fn_lasso_1<-rep(0,200)
tp_lasso_1<-rep(0,200)

nmp_lasso_1<-matrix(0,nrow = 3,ncol = 4)
fdr_lasso_1<-matrix(0,nrow = 3,ncol = 4)
power_lasso_1<-matrix(0,nrow = 3,ncol = 4)


for (i in 1:3) 
{
  for(k in 1:4)
   {
    print(k)
    for (j in 1:200)
      {
        X=matrix(data=NA,n[k],n[k])
        beta=rep(NA,p[k])
        Y=rep(NA,n[k])
        c(X,beta,Y):=data_gen_1(n[k],p[k],p_0[i])
        
        model_rl<-glmnet(X,(rank(Y)/n[k]-0.5),family = "gaussian",lambda = lambda_rl(p[k],n[k]),intercept = FALSE)
        beta_est_rl<-model_rl$beta
        
        fp_rl_1[j]<-sum(beta_est_rl[(p_0[i]+1):p[k]]!=beta[(p_0[i]+1):p[k]])
        fn_rl_1[j]<-sum(beta_est_rl[(1:p_0[i])]==0)
        tp_rl_1[j]<-sum(beta_est_rl[(1:p_0[i])]!=0)
        
         model_arl<-glmnet(X,(rank(Y)/n[k]-0.5),family = "gaussian",lambda = 2*lambda_rl(p[k],n[k]),intercept = FALSE,penalty.factor =   weights_arl(lambda=lambda_rl(p[k],n[k]),as.array(beta_est_rl)))
        beta_est_arl<-model_arl$beta
        
        fp_arl_1[j]<-sum(beta_est_arl[(p_0[i]+1):p[k]]!=beta[(p_0[i]+1):p[k]])
        fn_arl_1[j]<-sum(beta_est_arl[(1:p_0[i])]==0)
        tp_arl_1[j]<-sum(beta_est_arl[(1:p_0[i])]!=0)
        
        model_thrl<-cv.glmnet(X,(rank(Y)/n[k]-0.5),family = "gaussian")
        beta_est_thrl<-model_thrl$glmnet.fit$beta[,model_thrl$index[1]]
        ordered_beta_est_thrl<-beta_est_thrl[order(beta_est_thrl,decreasing = TRUE)]
        beta_est_thrl[!(order(beta_est_thrl,decreasing = TRUE) <= sum(beta_est_arl!=0))]<-0
        
        fp_thrl_1[j]<-sum(beta_est_thrl[(p_0[i]+1):p[k]]!=beta[(p_0[i]+1):p[k]])
        fn_thrl_1[j]<-sum(beta_est_thrl[(1:p_0[i])]==0)
        tp_thrl_1[j]<-sum(beta_est_thrl[(1:p_0[i])]!=0)
    
        
        model_lad<-glmnet(X,Y,family = "gaussian",lambda = lambda_lad(p[k],n[k]),intercept = FALSE)
        beta_est_lad<-model_lad$beta
        fp_lad_1[j]<-sum(beta_est_lad[(p_0[i]+1):p[k]]!=beta[(p_0[i]+1):p[k]])
        fn_lad_1[j]<-sum(beta_est_lad[(1:p_0[i])]==0)
        tp_lad_1[j]<-sum(beta_est_lad[(1:p_0[i])]!=0)
        
        model_lasso<-cv.glmnet(X,Y,family="gaussian")
        beta_est_lasso<-model_lasso$glmnet.fit$beta[,model_lasso$index[1]]
        fp_lasso_1[j]<-sum(beta_est_lasso[(p_0[i]+1):p[k]]!=beta[(p_0[i]+1):p[k]])
        fn_lasso_1[j]<-sum(beta_est_lasso[(1:p_0[i])]==0)
        tp_lasso_1[j]<-sum(beta_est_lasso[(1:p_0[i])]!=0)
    
      }
    nmp_1[i,k]<-mean(fp_rl_1+fn_rl_1)
    fdr_1[i,k]<-mean(fp_rl_1/(fp_rl_1+tp_rl_1))
    power_1[i,k]<-mean(tp_rl_1/p_0[i])
    
    nmp_arl_1[i,k]<-mean(fp_arl_1+fn_arl_1)
    fdr_arl_1[i,k]<-mean(fp_arl_1/(fp_arl_1+tp_arl_1))
    power_arl_1[i,k]<-mean(tp_arl_1/p_0[i])
    
    nmp_thrl_1[i,k]<-mean(fp_thrl_1+fn_thrl_1)
    fdr_thrl_1[i,k]<-mean(fp_thrl_1/(fp_thrl_1+tp_thrl_1))
    power_thrl_1[i,k]<-mean(tp_thrl_1/p_0[i])
    
    nmp_lad_1[i,k]<-mean(fp_lad_1+fn_lad_1)
    fdr_lad_1[i,k]<-mean(fp_lad_1/(fp_lad_1+tp_lad_1))
    power_lad_1[i,k]<-mean(tp_lad_1[j]/p_0[i])
    
    nmp_lasso_1[i,k]<-mean(fp_lasso_1+fn_lasso_1)
    fdr_lasso_1[i,k]<-mean(fp_lasso_1/(fp_lasso_1+tp_lasso_1))
    power_lasso_1[i,k]<-mean(tp_lasso_1[j]/p_0[i])
   }
}

```


```{r}
library(reshape2)
library(ggplot2)
output1 <- mget(load("output-1.RData", envir=(NE. <- new.env())), envir=NE.)
output2 <- mget(load("output-2.RData", envir=(NE. <- new.env())), envir=NE.)
output3 <- mget(load("output-3.RData", envir=(NE. <- new.env())), envir=NE.)
output4 <- mget(load("output-4.RData", envir=(NE. <- new.env())), envir=NE.)

nmp_plot1<-cbind(output1[[1]][1,],output1[[4]][1,],output1[[7]][1,],output1[[10]][1,])
colnames(nmp_plot1)<-c("rL","arL","thrL","cv")
nmp_plot1 <- melt(nmp_plot1,value.name = "NMP")
nmp_plot1<-cbind(nmp_plot1[,-1],rep(p,4))
colnames(nmp_plot1)<-c("Method","NMP","p")
p1<-ggplot(nmp_plot1, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot1<-cbind(output1[[1]][2,],output1[[4]][2,],output1[[7]][2,],output1[[10]][2,])
colnames(nmp_plot1)<-c("rL","arL","thrL","cv")
nmp_plot1 <- melt(nmp_plot1,value.name = "NMP")
nmp_plot1<-cbind(nmp_plot1[,-1],rep(p,4))
colnames(nmp_plot1)<-c("Method","NMP","p")
p2<-ggplot(nmp_plot1, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot1<-cbind(output1[[1]][3,],output1[[4]][3,],output1[[7]][3,],output1[[10]][3,])
colnames(nmp_plot1)<-c("rL","arL","thrL","cv")
nmp_plot1 <- melt(nmp_plot1,value.name = "NMP")
nmp_plot1<-cbind(nmp_plot1[,-1],rep(p,4))
colnames(nmp_plot1)<-c("Method","NMP","p")
p3<-ggplot(nmp_plot1, aes(p,NMP)) + geom_line(aes(colour = Method))


nmp_plot2<-cbind(output2[[1]][1,],output2[[4]][1,],output2[[7]][1,],output2[[10]][1,])
colnames(nmp_plot2)<-c("rL","arL","thrL","cv")
nmp_plot2 <- melt(nmp_plot2,value.name = "NMP")
nmp_plot2<-cbind(nmp_plot2[,-1],rep(p,4))
colnames(nmp_plot2)<-c("Method","NMP","p")
p4<-ggplot(nmp_plot2, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot2<-cbind(output2[[1]][2,],output2[[4]][2,],output2[[7]][2,],output2[[10]][2,])
colnames(nmp_plot2)<-c("rL","arL","thrL","cv")
nmp_plot2 <- melt(nmp_plot2,value.name = "NMP")
nmp_plot2<-cbind(nmp_plot2[,-1],rep(p,4))
colnames(nmp_plot2)<-c("Method","NMP","p")
p5<-ggplot(nmp_plot2, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot2<-cbind(output2[[1]][3,],output2[[4]][3,],output2[[7]][3,],output2[[10]][3,])
colnames(nmp_plot2)<-c("rL","arL","thrL","cv")
nmp_plot2 <- melt(nmp_plot2,value.name = "NMP")
nmp_plot2<-cbind(nmp_plot2[,-1],rep(p,4))
colnames(nmp_plot2)<-c("Method","NMP","p")
p6<-ggplot(nmp_plot2, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot3<-cbind(output3[[1]][1,],output3[[4]][1,],output3[[7]][1,],output3[[10]][1,])
colnames(nmp_plot3)<-c("rL","arL","thrL","cv")
nmp_plot3 <- melt(nmp_plot3,value.name = "NMP")
nmp_plot3<-cbind(nmp_plot3[,-1],rep(p,4))
colnames(nmp_plot3)<-c("Method","NMP","p")
p7<-ggplot(nmp_plot3, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot3<-cbind(output3[[1]][2,],output3[[4]][2,],output3[[7]][2,],output3[[10]][2,])
colnames(nmp_plot3)<-c("rL","arL","thrL","cv")
nmp_plot3 <- melt(nmp_plot3,value.name = "NMP")
nmp_plot3<-cbind(nmp_plot3[,-1],rep(p,4))
colnames(nmp_plot3)<-c("Method","NMP","p")
p8<-ggplot(nmp_plot3, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot3<-cbind(output3[[1]][3,],output3[[4]][3,],output3[[7]][3,],output3[[10]][3,])
colnames(nmp_plot3)<-c("rL","arL","thrL","cv")
nmp_plot3 <- melt(nmp_plot3,value.name = "NMP")
nmp_plot3<-cbind(nmp_plot3[,-1],rep(p,4))
colnames(nmp_plot3)<-c("Method","NMP","p")
p9<-ggplot(nmp_plot3, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot4<-cbind(output4[[1]][1,],output4[[4]][1,],output4[[7]][1,],output4[[10]][1,])
colnames(nmp_plot4)<-c("rL","arL","thrL","cv")
nmp_plot4 <- melt(nmp_plot4,value.name = "NMP")
nmp_plot4<-cbind(nmp_plot4[,-1],rep(p,4))
colnames(nmp_plot4)<-c("Method","NMP","p")
p10<-ggplot(nmp_plot4, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot4<-cbind(output4[[1]][2,],output4[[4]][2,],output4[[7]][2,],output4[[10]][2,])
colnames(nmp_plot4)<-c("rL","arL","thrL","cv")
nmp_plot4 <- melt(nmp_plot4,value.name = "NMP")
nmp_plot4<-cbind(nmp_plot4[,-1],rep(p,4))
colnames(nmp_plot4)<-c("Method","NMP","p")
p11<-ggplot(nmp_plot4, aes(p,NMP)) + geom_line(aes(colour = Method))

nmp_plot4<-cbind(output4[[1]][3,],output4[[4]][3,],output4[[7]][3,],output4[[10]][3,])
colnames(nmp_plot4)<-c("rL","arL","thrL","cv")
nmp_plot4 <- melt(nmp_plot4,value.name = "NMP")
nmp_plot4<-cbind(nmp_plot4[,-1],rep(p,4))
colnames(nmp_plot4)<-c("Method","NMP","p")
p12<-ggplot(nmp_plot4, aes(p,NMP)) + geom_line(aes(colour = Method))


figure <- ggarrange(p1, p2, p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,labels=c("independent, p0=3","independent, p0=10","independent, p0=20","SNP, p0=3","SNP, p0=10","SNP, p0=20","correlated, p0=3","correlated, p0=10","correlated, p0=20","exp, correlated, p0=3","exp, correlated, p0=10","exp, correlated, p0=20"),ncol = 3, nrow = 4,common.legend = TRUE, font.label = list(size=7),hjust=-1,vjust=1)
figure

```

